input_Username = "//*[@id='username']"
input_Password = "//*[@id='password']"
input_Submit = "//*[@id='login-submit']"
link_Username = "//*[@id='loggedas']/a"
link_Logout = "//*[@id='account']/ul/li[2]/a"
message_Success = "//*[@id='flash_notice']"
link_News = "//a[text()='Annonces']"
link_NewAnnouncement = "//*[@id='content']/div[1]/a"
input_AnnouncementTitle = "//*[@id='news_title']"
input_AnnouncementSummary = "//*[@id='news_summary']"
input_AnnouncementDescription = "//*[@id='news_description']"
input_CreateAnnouncement = "//*[@id='news-form']/input[3]"
link_DeleteAnnouncement = "//a[@data-method='delete']"

